config/routes.rb
BackgroundSpike::Application.routes.draw do
  resources :species

  resources :dinosaurs

  resources :batches

  match 'spawn_preview' => 'dinosaurs#spawn_preview', :via => :get
  match 'spawning_results' => 'dinosaurs#spawning_results'
  match 'query_batch/:id' => 'batches#query_batch'

end

app/models/batch.rb
class Batch < ActiveRecord::Base
  has_many :dinosaurs
end

app/models/dinosaur.rb
class Dinosaur < ActiveRecord::Base
  belongs_to :species
  belongs_to :batch

  def self.spawn_dinos(dino_params, batch_id)

    sleep 10 # pretend that this method takes a long time
    dino_params.each do |dino|
      dino["batch_id"] = batch_id
    end
    Dinosaur.create(dino_params)
    batch = Batch.find_by_id(batch_id)
    batch.status = "success"
    batch.save!

  end
end

app/models/species.rb
class Species < ActiveRecord::Base
  has_many :dinosaurs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/batches_controller.rb
class BatchesController < ApplicationController
  respond_to :html, :json, :js

  def query_batch
      @batch = Batch.find(params[:id])
      respond_with @batch
  end

  def show
    @batch = Batch.find(params[:id])
    @dinosaurs = @batch.dinosaurs
    respond_with @dinosaurs
  end
end

app/controllers/dinosaurs_controller.rb
class DinosaursController < ApplicationController

  # GET /dinosaurs
  # GET /dinosaurs.json
  def index
    @dinosaurs = Dinosaur.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @dinosaurs }
    end
  end

  # GET /dinosaurs/1
  # GET /dinosaurs/1.json
  def show
    @dinosaur = Dinosaur.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @dinosaur }
    end
  end

  # GET /dinosaurs/new
  # GET /dinosaurs/new.json
  def new
    @dinosaur = Dinosaur.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @dinosaur }
    end
  end

  # GET /dinosaurs/1/edit
  def edit
    @dinosaur = Dinosaur.find(params[:id])
  end

  # POST /dinosaurs
  # POST /dinosaurs.json
  def create
    @dinosaur = Dinosaur.new(params[:dinosaur])

    respond_to do |format|
      if @dinosaur.save
        format.html { redirect_to @dinosaur, notice: 'Dinosaur was successfully created.' }
        format.json { render json: @dinosaur, status: :created, location: @dinosaur }
      else
        format.html { render action: "new" }
        format.json { render json: @dinosaur.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /dinosaurs/1
  # PUT /dinosaurs/1.json
  def update
    @dinosaur = Dinosaur.find(params[:id])

    respond_to do |format|
      if @dinosaur.update_attributes(params[:dinosaur])
        format.html { redirect_to @dinosaur, notice: 'Dinosaur was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @dinosaur.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dinosaurs/1
  # DELETE /dinosaurs/1.json
  def destroy
    @dinosaur = Dinosaur.find(params[:id])
    @dinosaur.destroy

    respond_to do |format|
      format.html { redirect_to dinosaurs_url }
      format.json { head :ok }
    end
  end

  def spawn_preview

  end

  # POST /spawning_results
  def spawning_results
    batch = Batch.create!(:status => "processing")
    @batch_id = batch.id

    Dinosaur.delay.spawn_dinos(params[:dino], @batch_id)

  end

end

app/controllers/species_controller.rb
class SpeciesController < ApplicationController
  # GET /species
  # GET /species.json
  def index
    @species = Species.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @species }
    end
  end

  # GET /species/1
  # GET /species/1.json
  def show
    @species = Species.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @species }
    end
  end

  # GET /species/new
  # GET /species/new.json
  def new
    @species = Species.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @species }
    end
  end

  # GET /species/1/edit
  def edit
    @species = Species.find(params[:id])
  end

  # POST /species
  # POST /species.json
  def create
    @species = Species.new(params[:species])

    respond_to do |format|
      if @species.save
        format.html { redirect_to @species, notice: 'Species was successfully created.' }
        format.json { render json: @species, status: :created, location: @species }
      else
        format.html { render action: "new" }
        format.json { render json: @species.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /species/1
  # PUT /species/1.json
  def update
    @species = Species.find(params[:id])

    respond_to do |format|
      if @species.update_attributes(params[:species])
        format.html { redirect_to @species, notice: 'Species was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @species.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /species/1
  # DELETE /species/1.json
  def destroy
    @species = Species.find(params[:id])
    @species.destroy

    respond_to do |format|
      format.html { redirect_to species_index_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dinosaurs_helper.rb
module DinosaursHelper
end

app/helpers/species_helper.rb
module SpeciesHelper
end

app/views/batches/show.html.erb
Dinos created in batch <%= @batch.id %>:

<%= render @dinosaurs %>

app/views/batches/show.js.erb
$('#dino_results').append('<div><%= escape_javascript(raw @dinosaurs.length) %> dinosaurs spawned!</div>');
$('#dino_results').append("<%= escape_javascript(raw render(@dinosaurs))%>");

app/views/dinosaurs/_dinosaur.html.erb
<div><%= link_to dinosaur.name, dinosaur_path(dinosaur) %>, <%= link_to dinosaur.species.common_name, species_path(dinosaur.species) %>, <%= dinosaur.species.era %></div>

app/views/dinosaurs/_form.html.erb
<%= form_for(@dinosaur) do |f| %>
  <% if @dinosaur.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dinosaur.errors.count, "error") %> prohibited this dinosaur from being saved:</h2>

      <ul>
      <% @dinosaur.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :favorite_food %><br />
    <%= f.text_field :favorite_food %>
  </div>
  <div class="field">
    <%= f.label :weight %><br />
    <%= f.number_field :weight %>
  </div>
  <div class="field">
    <%= f.label :color %><br />
    <%= f.text_field :color %>
  </div>
  <div class="field">
    <%= f.label :species_id %><br />
    <%= f.number_field :species_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dinosaurs/edit.html.erb
<h1>Editing dinosaur</h1>

<%= render 'form' %>

<%= link_to 'Show', @dinosaur %> |
<%= link_to 'Back', dinosaurs_path %>

app/views/dinosaurs/index.html.erb
<%= link_to 'Spawn many Dinosaurs', spawn_preview_path %>

<h1>Listing dinosaurs</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Favorite food</th>
    <th>Weight</th>
    <th>Color</th>
    <th>Species</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @dinosaurs.each do |dinosaur| %>
  <tr>
    <td><%= dinosaur.name %></td>
    <td><%= dinosaur.favorite_food %></td>
    <td><%= dinosaur.weight %></td>
    <td><%= dinosaur.color %></td>
    <td><%= dinosaur.species.common_name %></td>
    <td><%= link_to 'Show', dinosaur %></td>
    <td><%= link_to 'Edit', edit_dinosaur_path(dinosaur) %></td>
    <td><%= link_to 'Destroy', dinosaur, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Dinosaur', new_dinosaur_path %>

<%= link_to 'Spawn many Dinosaurs', spawn_preview_path %>

app/views/dinosaurs/new.html.erb
<h1>New dinosaur</h1>

<%= render 'form' %>

<%= link_to 'Back', dinosaurs_path %>

app/views/dinosaurs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @dinosaur.name %>
</p>

<p>
  <b>Favorite food:</b>
  <%= @dinosaur.favorite_food %>
</p>

<p>
  <b>Weight:</b>
  <%= @dinosaur.weight %>
</p>

<p>
  <b>Color:</b>
  <%= @dinosaur.color %>
</p>

<p>
  <b>Species:</b>
  <%= @dinosaur.species.common_name %>
</p>


<%= link_to 'Edit', edit_dinosaur_path(@dinosaur) %> |
<%= link_to 'Back', dinosaurs_path %>

app/views/dinosaurs/spawn_preview.html.erb
<div> Spawn Dinosaurs </div>

<%= form_tag spawning_results_path do %>
   <div>
     <%= text_field_tag 'dino[][name]','Denise' %>
     <%= text_field_tag 'dino[][species_id]','4' %>
     <%= text_field_tag 'dino[][name]','Tyran' %>
     <%= text_field_tag 'dino[][species_id]','1' %>
     <%= text_field_tag 'dino[][name]','Quentin' %>
     <%= text_field_tag 'dino[][species_id]','2' %>

   </div>
   <%= submit_tag("Spawn Dinos Now") %>
<% end %>

app/views/dinosaurs/spawning_results.html.erb
The batch id is: <%= @batch_id %>

<div id = "spawn" data-id="<%= @batch_id %>">Spawning...</div>
<div id="dino_results"></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BackgroundSpike</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<% flash.each do |type, message| %>
    <div class="<%= type %>"><%= message %></div>
<% end %>
<%= yield %>

</body>
</html>

app/views/species/_form.html.erb
<%= form_for(@species) do |f| %>
  <% if @species.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@species.errors.count, "error") %> prohibited this species from being saved:</h2>

      <ul>
      <% @species.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :scientific_name %><br />
    <%= f.text_field :scientific_name %>
  </div>
  <div class="field">
    <%= f.label :common_name %><br />
    <%= f.text_field :common_name %>
  </div>
  <div class="field">
    <%= f.label :era %><br />
    <%= f.text_field :era %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/species/edit.html.erb
<h1>Editing species</h1>

<%= render 'form' %>

<%= link_to 'Show', @species %> |
<%= link_to 'Back', species_index_path %>

app/views/species/index.html.erb
<h1>Listing species</h1>

<table>
  <tr>
    <th>Scientific name</th>
    <th>Common name</th>
    <th>Era</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @species.each do |species| %>
  <tr>
    <td><%= species.scientific_name %></td>
    <td><%= species.common_name %></td>
    <td><%= species.era %></td>
    <td><%= link_to 'Show', species %></td>
    <td><%= link_to 'Edit', edit_species_path(species) %></td>
    <td><%= link_to 'Destroy', species, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Species', new_species_path %>

app/views/species/new.html.erb
<h1>New species</h1>

<%= render 'form' %>

<%= link_to 'Back', species_index_path %>

app/views/species/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Scientific name:</b>
  <%= @species.scientific_name %>
</p>

<p>
  <b>Common name:</b>
  <%= @species.common_name %>
</p>

<p>
  <b>Era:</b>
  <%= @species.era %>
</p>


<%= link_to 'Edit', edit_species_path(@species) %> |
<%= link_to 'Back', species_index_path %>